# Prometheus Configuration for JLAM Local Development

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    
  - job_name: 'authentik'
    static_configs:
      - targets: ['authentik-server:9000']
    metrics_path: '/-/metrics/'
